package com.idbi.intech.oms.domain.app;

import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.idbi.intech.erm.domain.app.ActivityLogDto;
import com.idbi.intech.erm.domain.app.CommentDto;
import com.idbi.intech.erm.domain.app.FileMasterDto;
import com.idbi.intech.erm.domain.app.UserDto;

import lombok.Data;

@Data
public class OmsAlertMasterDto {
	private String alertId;
	private String custId;
	private String custAcid;
	private String ruleId;
	private String alertCat;
	private String ruleRisk;
	private String alertStatus;
	private String actUserId;
	private String alertVal;
	private String lastUserId;
	private String branchId;
	private String region;
	private String zone;
	private String generatedTime;
	private String custVertical;
	private Date lastChangeTime;
	private String actRoleId;
	private String custName;
	private String ruleClassification;
	private List<OmsAlertMasterDto> alertList;
	private HashMap<String, String> alertData;
	private UserDto userDto;
	private ActivityLogDto activityLogDto;
	private CommentDto commentDto;
	private RuleMasterDto ruleMasterDto;
	private String riskCol;
	private String recordStatusCol;
	private String officeType;
	private String action;
	private String searchParam;
	private String searchValue;
	private Set<String> paramValueList;
	private List<RuleMasterDto> ruleList;
	private List<AmlAcMasterDto> amlAcList;
	private String selectedRole;
	@JsonFormat(pattern = "dd-MM-yyyy")
	private Date futureDate;
	private String accountNo;
	private String assignedUser;
	private String reportingUser;
	private Set<String> reportingUserSet;
	private String searchUserId;
	private String variable;
	private String ruleDesc;

	private String userId;
	private List<String> alertReportRulewiseList;
	private List<AMLCustMasterDto> custList;
	private String ruleTat;
	private String recurrenceCnt;
	private List<OmsBranchMasterDto> branchDtoList;
	private List<OmsBranchMasterDto> regionDtoList;
	private String zoneId;
	private String regionId;
	private OmsBranchMasterDto branchDto;
	private String startDate;
	private String endDate;
	private List<OmsAlertMasterDto> alertRuleList;
	private String comment;
	private String branchName;
	private String alertTat;
	private String closeLastChangeTime;
	private List<OmsAuditDto> zoneAlertCountList;
	private List<OmsAuditDto> regionAlertCountList;
	private List<String> regionAlertCount;
	private List<OmsAuditDto> branchAlertCountList;
	private List<OmsAuditDto> ruleAlertCountList;
	private List<OmsAlertMasterDto> accountAlertCountList;
	private Date fromDate;
	private Date toDate;
	private List<String> zoneAlertCount;
	private List<OmsAlertMasterDto> recurrenceList;
	private String ruleName;
	private String userPosition;
	private String countObj;
	private List<AlertTransferDto> alertTransferDtoList;
	private List<String> branchDrpdownList;
	private List<String> tatReportList;
	private String lastThreeExecutedCount;
	private List<RoleVerticalMapperDto> roleDtoList;
	private String roleName;
	private String agmName;
	private String dgmName;
	private String rmName;
	private String dealingVertical;
	private boolean aggFlg;
	private String riskType;
	private List<String> alertReportRiskwiseList;
	private String ruleFrequency;
	private String acctName;
	private String sourceTxt;
	private String romDashboard;

	private String status;
	private String searchRuleRisk;
	private String selectedFlag;
	private List<String> viewByList;
	private List<String> classificationList;
	private List<String> riskList;
	private List<String> priorityList;
	private List<String> classificationGraphList;
	private String btnColor;

	private String reportType;
	private Integer oneDayCountTotal;
	private Integer oneWeekCountTotal;
	private Integer gtOneWeekltTwoWeekTotal;
	private Integer gtTwoWeekltOneMonthTotal;
	private Integer gtOneMonthltThreeMonthTotal;
	private Integer gtThreeMonthltSixMonthTotal;
	private Integer gtSixMonthltOneYearTotal;
	private Integer gtOneYearsTotal;
	private Integer perRuleCountTotal;
	private Integer oneDayCount;
	private Integer oneWeekCount;
	private Integer gtOneWeekltTwoWeek;
	private Integer grandTotal;
	private String commentedBy;
	private String commentedDate;
	private String assetOperationFlg;
	private String omsOfficeType;
	private List<FileMasterDto> filedetails;
	private String zomDashboardParam;

	private List<String> newPriorityList;
	private List<String> newClassificationGraphList;
	private List<VerticalExcelExportDto> verticalExportDto;
	private List<String> zonePieGraphList;
	private String auditSearchParam;
	private List<ConsolidatedViewDto> consolidatedReportList;
	private List<RomReportDto> reportList;
	private String ageValue;
	private String reckeckRequiredFlg;
	private String falseClosure;
	private List<String> commentByName;
	private String zoneName;
	private Set<OmsBranchMasterDto> regionDtoList1;
	private String excemptFlg;
	private int totalCount;
	private int openCount;
	private int closeCount;
	private int escalateCount;
	private String userEin;
	private String userName;
	private String regionName;
	private String userEmail;
	private String tranId;
	private String tranDate;
	private String tranAmt;
	private List<OmsAlertMasterDto> omsAlerData;
	private String partTranType;
	private String tranParticular;
	private String rulePriority;
	private String ruleStatus;
	private String fDate;
	private String sDate;
	private String tDate;
	private Set<OmsAlertMasterDto> ruleAndDayWiseCount;
	private int firstCount;
	private int secondCount;
	private int thirdCount;
	private String gen;
	private String inTat;
	private String inTatPer;
	private List<OmsAlertMasterDto> omsTatReportList;
	private int[] classificationDetails;
	private Date expectedClosureDate;

	private String inMonthCount;
	private String beforeMonthCount;
	private String year;
	private String month;
}